db:
  host: "localhost"
  port: "5432"
  name: "go_crawler"
  username: "postgres"
  password: "postgres"
  ssl_mode: "disable"

tor:
  exe_path: "D:/Tor Browser/Browser/TorBrowser/Tor/tor.exe"
  data_dir : ""